---
- hosts: {{environment}}
  remote_user: jenkins
  tasks:

    - name: stop application
      shell: /opt/cicd-lab-backend/application.sh stop

    - name: delete artifact
      shell: rm /opt/cicd-lab-backend/cicd-lab-backend*.jar
      ignore_errors: yes

    - name: copy artifact from Nexus
      get_url:
        url=http://192.168.33.10:8081/nexus/service/local/repositories/releases/content/se/omegapoint/cicd-lab-backend/1.0.{{build_version}}/cicd-lab-backend-1.0.{{build_version}}.jar
        dest=/opt/cicd-lab-backend

    - name: start application
      shell: /opt/cicd-lab-backend/application.sh start
