---
- hosts: "{{environment}}"
  remote_user: jenkins
  tasks:

    - name: stop application
      service: name=cicd-lab-backend state=stopped

# task: delete artifact

# task: copy artifact (from Jenkins or Nexus)

# task: start application
